### ISSUE TITLE
pappy-proxy's missing deps

### ISSUE THREAD

**Issue by hexcat** [BlackArch/blackarch#1136]
pappy-proxy is missing these dependencies which aren't in repos:
- scrypt>=0.7.1
- txsocksx>=1.15.0.2

And these are missing dependencies which are in repos but not listed as deps:
- python2-scrypt
- python2-decorator

**Comment by noptrix** [comment]
thank you for reporting this. will be fixed.

**Comment by noptrix** [comment]
fixed and released

**Comment by hexcat** [comment]
pappy still fails to start due to missing txsocksx (not in repositories) :
`pkg_resources.DistributionNotFound: The 'txsocksx>=1.15.0.2' distribution was not found and is required by pappyproxy`

**Comment by noptrix** [comment]
ok, fixed now  :)
