### ISSUE TITLE
Gobuster not receiving update to v3

### ISSUE THREAD

**Issue by aancw** [BlackArch/blackarch#2465]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description
Gobuster package still getting version v2.0.1 instead of v3 as gobuster repo update.

### Steps to reproduce
- pacman -Syu
- pacman -S gobuster

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

```
↳ pacman -Q --info gobuster
Name            : gobuster
Version         : 1:281.f7ed22d-1
Description     : Directory/file & DNS busting tool written in Go.
Architecture    : x86_64
URL             : https://github.com/OJ/gobuster
Licenses        : APACHE
Groups          : blackarch  blackarch-webapp  blackarch-scanner
Provides        : None
Depends On      : glibc
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 5.28 MiB
Packager        : Levon Kayan <noptrix@nullsecurity.net>
Build Date      : Thu 25 Jul 2019 05:59:49 PM WIB
Install Date    : Mon 09 Sep 2019 03:27:54 PM WIB
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature

↳ gobuster -w directory-list-2.3-medium.txt -u http://example.com/ -x php -fw

=====================================================
Gobuster v2.0.1              OJ Reeves (@TheColonial)
```

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

```
gobuster dir -u https://buffered.io -w ~/wordlists/shortlist.txt -l

===============================================================
Gobuster v3.0.1
by OJ Reeves (@TheColonial) & Christian Mehlmauer (@_FireFart_)
===============================================================
```

### Info for developers

**Device:** Manufacturer Model XVI (Only if you consideer needed, for example, network cards)
**GNU/Linux distribution:** Archlinux with BlackArch Repo
**Tool version:** 2.0.1

**Comment by noraj** [comment]
I'm wondering why, upstream seems ok.

https://github.com/OJ/gobuster/blob/f7ed22d11ebacf174e00bbab308dfe72e45b3d50/cli/gobuster.go#L19

https://github.com/OJ/gobuster/blob/f7ed22d11ebacf174e00bbab308dfe72e45b3d50/libgobuster/version.go#L5

**Comment by noptrix** [comment]
@aancw sorry we compeltely forgot this. fixed/changed/update with https://github.com/BlackArch/blackarch/commit/969af49634c1bf49385bb83abd441b6c03249070

**Comment by forstern** [comment]
when will this be available? still have the same issue :(

**Comment by noptrix** [comment]
@forstern hm? it is fixed and released since 19 days: https://github.com/BlackArch/blackarch/commit/969af49634c1bf49385bb83abd441b6c03249070

**Comment by forstern** [comment]
Well after doing a yay -S gobuster i still get:

```
=====================================================
Gobuster v2.0.1              OJ Reeves (@TheColonial)
=====================================================
[+] Mode         : dir
[+] Url/Domain   : <domain>
[+] Threads      : 10
[+] Wordlist     : <wordlist>
[+] Status codes : 200,204,301,302,307,403
[+] Timeout      : 10s
=====================================================
```

Installing it with:
```
yay -S gobuster
resolving dependencies...
looking for conflicting packages...

Packages (1) gobuster-1:291.d41729a-1

Total Installed Size:  7.09 MiB
```

I even manually removed all go bins and src related to gobuster.

**Comment by noraj** [comment]
@forstern seems to be the same problem as #2456 the tool is update but the version displayed in the help message is not the correct one. Seems to be some go-lang blackmagic.
