### ISSUE TITLE
blackarch-isntall chroot: failed to run command

### ISSUE THREAD

**Issue by kylian001** [BlackArch/blackarch#2872]
Wen runing `blackarch-install` all goes well untill it is starting to install the base system then it gets stuck in a infinity loop that says
`Chroot: failed to run command `passwd` : No such file or directory`

**Comment by Edu4rdSHL** [comment]
@kylian001 thanks for reporting. Can you please follow the instructions listed [here](https://github.com/BlackArch/blackarch-installer#using-the-git-version) and tell me if this works now?

**Comment by kylian001** [comment]
well i dont even set the root passwd yet it automaticly goes forward and hits that error. any work around?

```
[+] setting up root account

cp: cannot create directory `/mnt/root/.` No such file or directory
```

then the error apears.

**Comment by Edu4rdSHL** [comment]
Seeing that message, I assume that the problem is because there was an error when mounting the filesystems but the installer continued despite it. This problem should be fixed with https://github.com/BlackArch/blackarch-installer/commit/8589e7245866cdd3dc202e2dca2596679a6a39fa and https://github.com/BlackArch/blackarch-installer/commit/fd7f043088c958789aeab6546f77fb315120670b.

I have updated the blackarch-installer package and should be in the repos soon. I will levae this issue open until I receive confirmation from you.

**Comment by kylian001** [comment]
> Seeing that message, I assume that the problem is because there was an error when mounting the filesystems but the installer continued despite it. This problem should be fixed with [BlackArch/blackarch-installer@8589e72](https://github.com/BlackArch/blackarch-installer/commit/8589e7245866cdd3dc202e2dca2596679a6a39fa) and [BlackArch/blackarch-installer@fd7f043](https://github.com/BlackArch/blackarch-installer/commit/fd7f043088c958789aeab6546f77fb315120670b).
> 
> I have updated the blackarch-installer package and should be in the repos soon. I will levae this issue open until I receive confirmation from you.

I have used the git version and that seem to work. i dont use the repo version because i have to do pacman -Syu before it and that takes ages because of the thousonds of errors.

**Comment by Edu4rdSHL** [comment]
No problem, I assume this issue is fixed, if you get it again, let me know to re-open.

Thank you for reporting.

**Comment by JoeStagner** [comment]
Using the lasted iso installing in Virtualbox on a Mac I still get this error loop.

Can anyone advise a work around ?

**Comment by ikstream** [comment]
Have you tried updating the installer before using it?
Did you get the iso from blackarch.org?
Which version is it (Datestring, netinstall/full)?

If it doesn't help, you could also try the calamaris installer on the slim iso.

**Comment by noraj** [comment]
Which kind of Mac is it? New ones with M1 (ARM) chips?

**Comment by DeeDash** [comment]
Trying to use the Netinstall on bare-metal and I face the same error, right after it finishes downloading the base and other packages. I have not selected its option to look for best servers. 
I'll try using the full ISO and edit this post later [ flashing 17 gigs is painfully slow :( ]

**Comment by lexy37** [comment]
Just install python " pacman  -Sy python" before running blackarch-install, this worked for me.

**Comment by theEndurance-del** [comment]
> Using the lasted iso installing in Virtualbox on a Mac I still get this error loop.
> 
> Can anyone advise a work around ?

I tried running the installer on Windows too... `chroot` still failed.
I used the `netinstall` ISO, the datestring was `2021.09.01`.
Architecture is `x86-64`

**Comment by ikstream** [comment]
Please run `pacman -Syy archlinux-keyring blackarch-keyring` before running the installer

**Comment by oscar230** [comment]
> Please run `pacman -Syy archlinux-keyring blackarch-keyring` before running the installer

Thanks, this solved the problem for me with blackarch-linux-netinst-2021.09.01-x86_64.

**Comment by dualfade** [comment]
This probably should be added right on the Download / Installation page as trouble shooting / first things first. Update your BlackArch Keyring. Thoughts ?
Here -> https://www.blackarch.org/downloads.html

~!>D------- Original Message -------

**Comment by Zuribraya2020** [comment]
Created a GitHub account just to say thanks and that this worked. Please run pacman -Syy archlinux-keyring blackarch-keyring before running the installer.

**Comment by rmcmillan34** [comment]
Hey all, 
If you cannot run `pacman -Syy archlinux-keyring blackarch-keyring` because you don't have your network configured. Run the installer up until the network is configured then CTRL+C to interrupt the installer, then run the pacman command. 
Install worked like a charm after that.
