### ISSUE TITLE
Dependencies unsatisfied when i install blackarch on arch linux use linux-zen kernel ,how can i fix it,bro?

### ISSUE THREAD

**Issue by Kali-Ivypooler** [BlackArch/blackarch#4141]
Type: Question

## Question

:: Do you want to skip the above packages for this upgrade? [y/N] 
error: failed to prepare transaction (could not satisfy dependencies)
:: unable to satisfy dependency 'python-boto' required by aws-extender-cli
:: unable to satisfy dependency 'python-flickrapi' required by kamerka

==> WARNING: Using existing $srcdir/ tree
==> Removing existing $pkgdir/ directory...
==> Starting check()...
nose command: /home/ivypooler/.cache/yay/python-boto/src/boto-2.49.0.20190327/tests/test.py -a !notdefault tests/unit
/home/ivypooler/.cache/yay/python-boto/src/boto-2.49.0.20190327/boto/__init__.py:1105: SyntaxWarning: invalid escape sequence '\c'
  """
/home/ivypooler/.cache/yay/python-boto/src/boto-2.49.0.20190327/boto/pyami/config.py:98: SyntaxWarning: invalid escape sequence '\s'
  match = re.match("^#import[\s\t]*([^\s^\t]*)[\s\t]*$", line)
E
======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'boto.vendored.six.moves')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3.12/site-packages/nose/loader.py", line 416, in loadTestsFromName
    module = self.importer.importFromPath(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/nose/importer.py", line 162, in importFromPath
    return self.importFromDir(dir_path, fqname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/nose/importer.py", line 209, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/nose/importer.py", line 117, in load_module
    return load_package(name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/nose/importer.py", line 71, in load_package
    spec.loader.exec_module(sys.modules[name])
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ivypooler/.cache/yay/python-boto/src/boto-2.49.0.20190327/tests/unit/__init__.py", line 1, in <module>
    from boto.compat import http_client
  File "/home/ivypooler/.cache/yay/python-boto/src/boto-2.49.0.20190327/boto/__init__.py", line 27, in <module>
    from boto.pyami.config import Config, BotoConfigLocations
  File "/home/ivypooler/.cache/yay/python-boto/src/boto-2.49.0.20190327/boto/pyami/config.py", line 29, in <module>
    from boto.compat import expanduser, ConfigParser, NoOptionError, NoSectionError, StringIO
  File "/home/ivypooler/.cache/yay/python-boto/src/boto-2.49.0.20190327/boto/compat.py", line 52, in <module>
    from boto.vendored.six.moves import filter, http_client, map, _thread, \
ModuleNotFoundError: No module named 'boto.vendored.six.moves'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
==> ERROR: A failure occurred in check().
    Aborting...
 -> error making: python-boto-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
python-boto - exit status 4

**Comment by noraj** [comment]
I guess for aws-extender-cli we should migrate to [python-boto3](https://archlinux.org/packages/extra/any/python-boto3/) and [python-flickrapi](https://aur.archlinux.org/packages/python-flickrapi) was drop to AUR so we should package it if we still want to support kamerka.

**Comment by noraj** [comment]
- [aws-extender-cli](https://github.com/VirtueSecurity/aws-extender-cli/blob/master/requirements.txt) requires both boto and boto3
- [aws-extender-cli](https://github.com/VirtueSecurity/aws-extender-cli/) has not been updated for 4 years
- upstream [boto](https://github.com/boto/boto) was archived and deprecated on May 10, 2024
- [python-boto](https://github.com/BlackArch/blackarch/tree/master/packages/python-boto) is no longer building

**Comment by noraj** [comment]
- [python-flickrapi](https://github.com/BlackArch/blackarch/tree/master/packages/python-flickrapi) is building
- [kamerka](https://github.com/BlackArch/blackarch/tree/master/packages/kamerka) is not building
- commit https://github.com/woj-ciech/kamerka/commit/d5fe254aa3b4f1f5ef82fff8ab42de7d394343a9 deleted the script
- I'll make a PR to use commit 40

**Comment by Kali-Ivypooler** [comment]
I'm new to it,if fixed,please kick me,thanks!

**Comment by noraj** [comment]
kamerka is fixed now, aws-extender-cli is hardly fixable, I advise to remove it if you want to upgrade

**Comment by Mastrota** [comment]
`:: unable to satisfy dependency 'python-boto' required by aws-extender-cli` 
Problem persist need python-boto3 and new packages aws-cli

**Comment by D3vil0p3r** [comment]
@noraj we can close this issue imho https://github.com/BlackArch/blackarch/pull/4285
