### ISSUE TITLE
Eyewitness missing the modules folder

### ISSUE THREAD

**Issue by Oweoqi** [BlackArch/blackarch#925]
Hey guys,

Looks like eyewitness is missing it's modules folder:

$ eyewitness 
Traceback (most recent call last):
  File "EyeWitness.py", line 13, in <module>
    from modules import db_manager
ImportError: No module named modules

According to the git page https://github.com/ChrisTruncer/EyeWitness, the modules folder should be in the root of eyewitness.py but if we look at the dir in blackarch /usr/share/eyewitness/, it's not there:

$ ls
EyeWitness.py  signatures.txt

**Comment by noptrix** [comment]
will be fixed, thx.

**Comment by Oweoqi** [comment]
Hey, I was playing with this onsite today, I noticed a few more missing dependencies:

python-pip xvfb python-netaddr python-dev

I suppose python-pip is subjective, but it looks needed to get the following:

python_qt_binding
fuzzywuzzy
selenium
python-Levenshtein
pyasn1
pyvirtualdisplay

Also this module: https://github.com/ChrisTruncer/rdpy.git

Full install script for reference: https://github.com/ChrisTruncer/EyeWitness/blob/master/setup/setup.sh

**Comment by noptrix** [comment]
this has been fixed

**Comment by Oweoqi** [comment]
hey dude, looks like you forgot the rdp libraries:

$ eyewitness 
[*] RDP libraries not found.
[*] Please run the script in the setup directory!

**Comment by noptrix** [comment]
ups. gonna fix it. thx!

**Comment by Oweoqi** [comment]
confirmed its all good now
